### ISSUE TITLE
Dimension editing and text displaying

### ISSUE THREAD

**Issue by ClassyWeasel** [valendinosaurus/lego-label-maker#1]
So far, great work! There's a lot more here than I would have thought of, and I would totally use this to build labels for my drawers once all the kinks have been worked out. A few things though:

1. When choosing the ratio width and height, it's a bit unclear what I'm really doing. Is this in inches or cm, or is it just the ratio of the label on a standard 8.5x11 sheet of paper? If that's the case, it doesn't appear to keep my ratio whenever I adjust the number of labels on the row and/or column. For example, if I add one row to the page, it shrinks all the other rows in order to fit, thus ruining my label ratio. I'm not sure if that's how the final product will look, or if it's just a visual bug.

2. I like adding text to the label, but the formatting is a bit off-center. Not sure if this is possible, but I'd like there to be an option for a text box of sorts, where I can bold or italicize, maybe even mess with font size and text alignment.

3. The horizontal/vertical radio buttons don't seem to be working whenever I attempt to edit the labels. I'm guessing that if I press vertical, the dimension and color sections of the label will appear beneath the LEGO image, but that isn't happening.

For now, that's all the feedback I've got, great job so far! Keep it up, and I'd be happy to take a look at it some more as this project continues.

**Comment by valendinosaurus** [comment]
Hi ClassyWeasel

Thanks for the inputs. Here are some comments regarding to your points:

1. This is indeed a bit confusing: the main thought for the ratio is to be very independent of units, meaning that it should not matter if you have A4 or a small label in mind, you can just enter the ratio of your desired output. But, at the moment the ratio is referring to the whole group of labels, not a single one. Would it be more comfortable to define the ratio of the single label itself, and then calculate the whole group depending on this? Or even to choose if the ratio should be applied to a single label or the whole group? I could also define some presets like A4 and so on.
2. This is in my backlog. ATM, the textbox is very small (and the sizes of the three parts is not yet customizable). But I think it would also be great to add text beneath the images, right? 
3. That's right, this is not published yet, but I am working on it.


Thank you very much for the inputs!

**Comment by ClassyWeasel** [comment]
1. I agree, it would be a little easier to understand if the ratio referred to just one label, and then all the labels followed that ratio. Personally, I think the ratio should apply to every label in the group because if I wanted my labels to be different sizes, I'll just make another batch of them.
2. Absolutely, especially if my drawers are oddly shaped, I'd definitely like the ability to have text below the image.
3. Gotcha, happy to help!
